# Generated by Django 3.2.4 on 2024-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default-avatar_wh7ben', upload_to='images/'),
        ),
    ]
